/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "mac_correct.v:5.1-24.10" *)
module mac(clk, rst, a, b, out);
  (* src = "mac_correct.v:6.32-6.35" *)
  input clk;
  wire clk;
  (* src = "mac_correct.v:7.32-7.35" *)
  input rst;
  wire rst;
  (* src = "mac_correct.v:8.32-8.33" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "mac_correct.v:9.32-9.33" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "mac_correct.v:10.32-10.35" *)
  output [31:0] out;
  reg [31:0] out;
  (* src = "mac_correct.v:21.20-21.33" *)
  wire [31:0] _0_;
  (* src = "mac_correct.v:13.25-13.32" *)
  wire [15:0] product;
  assign _0_ = $signed(out) + (* src = "mac_correct.v:21.20-21.33" *) $signed(product);
  (* \always_ff  = 32'd1 *)
  (* src = "mac_correct.v:17.5-22.8" *)
  always @(posedge clk)
    if (rst) out <= 32'd0;
    else out <= _0_;
  assign product = $signed(a) * (* src = "mac_correct.v:15.22-15.27" *) $signed(b);
endmodule
