/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "mac_llm_A.v:1.1-21.10" *)
module mac(clk, rst, a, b, out);
  (* src = "mac_llm_A.v:2.33-2.36" *)
  input clk;
  wire clk;
  (* src = "mac_llm_A.v:3.33-3.36" *)
  input rst;
  wire rst;
  (* src = "mac_llm_A.v:4.32-4.33" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "mac_llm_A.v:5.32-5.33" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "mac_llm_A.v:6.32-6.35" *)
  output [31:0] out;
  reg [31:0] out;
  (* src = "mac_llm_A.v:17.20-17.54" *)
  wire [31:0] _0_;
  (* src = "mac_llm_A.v:9.25-9.32" *)
  wire [15:0] product;
  assign _0_ = out + (* src = "mac_llm_A.v:17.20-17.54" *) { product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product[15], product };
  (* \always_ff  = 32'd1 *)
  (* src = "mac_llm_A.v:13.5-19.8" *)
  always @(posedge clk)
    if (rst) out <= 32'd0;
    else out <= _0_;
  assign product = $signed(a) * (* src = "mac_llm_A.v:11.22-11.27" *) $signed(b);
endmodule
